apiVersion: apps/v1
kind: Deployment
metadata:
  name: billow-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billow-server
  template:
    metadata:
      labels:
        app: billow-server
    spec:
      containers:
        - name: billow-server-container
          image: handher0/billow-server:0.2 # 0.2 버전 사용
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # 헬스 체크
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30 # 컨테이너 시작 후 30초 기다렸다가 첫 체크 시작
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60 # 컨테이너 시작 후 60초 기다렸다가 첫 체크 시작
            periodSeconds: 15
            timeoutSeconds: 5
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: billow-secrets
                  key: JWT_SECRET_KEY
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: billow-secrets
                  key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: billow-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billow-secrets
                  key: DB_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"