# MySQL을 위한 내부 주소(Service) 생성
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
# MySQL 컨테이너 배포 (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billow-secrets
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: "billow"
          volumeMounts:
            - name: mysql-temp-storage
              mountPath: /var/lib/mysql
          readinessProbe:
            # 3306 포트로 TCP 연결을 시도해서 성공하면 준비된 것으로 간주
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15 # 파드 시작 후 15초 뒤에 첫 검사 시작
            periodSeconds: 10   # 10초마다 반복 검사
          livenessProbe:
              # 파드가 살아있는지 확인 (문제가 생기면 재시작)
              tcpSocket:
                port: 3306
              initialDelaySeconds: 20 # 파드 시작 후 20초 뒤에 첫 검사 시작
              periodSeconds: 10
      volumes:
        - name: mysql-temp-storage
          emptyDir: {}
---
# billow-server 배포 (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billow-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billow-server
  template:
    metadata:
      labels:
        app: billow-server
    spec:
      containers:
        - name: billow-server-container
          image: handher0/billow-server:1.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 20
          envFrom:
            - secretRef:
                name: billow-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
# '내부' 주소(Service) 생성
apiVersion: v1
kind: Service
metadata:
  name: billow-server-service
spec:
  type: ClusterIP
  selector:
    app: billow-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Ingress 규칙 생성
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billow-server-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: "billow.210-178-1-132.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: billow-server-service
                port:
                  number: 8080